theme: minima
title: Chris's Blog
author: crash0283
email: rasch83@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new blog!  I hope you like it!

# social links
twitter_username: @somehandle
github_username:  crash0283

show_excerpts: true # set to false to remove excerpts on the homepage
